### Functions

##### Numpy Methods

In [2]:
import numpy as np
import pandas as pd # used to help illustrate functions

# initialize basic numpy arrays
a = np.array([1, 2, 3], dtype="int16")

b = np.array([[1.0, 2.0, 3.0], 
              [9.0, 8.0, 7.0]])

print(f"List a: {a}")
print(f"List b: \n{b}")


List a: [1 2 3]
List b: 
[[1. 2. 3.]
 [9. 8. 7.]]


In [3]:
# np.array() methods

# a.ndim gets dimensions
# a.shape gets shape
# a.size == # of elements
# a.dtype == data type of elements
# a.itemsize == bytes per item
# a.nbytes == total bytes used == (a.itemsize * a.size)

# pandas used only to illustrate various property functions
listStats = [["a", a.ndim, a.shape, a.dtype, a.size, a.itemsize, a.nbytes],
             ["b", b.ndim, b.shape, b.dtype, b.size, b.itemsize, b.nbytes]]
df = pd.DataFrame(listStats, columns=["List", ".ndim", ".shape", ".dtype", ".size", ".itemsize", ".nbytes"])
print("\n", df)


   List  .ndim  .shape   .dtype  .size  .itemsize  .nbytes
0    a      1    (3,)    int16      3          2        6
1    b      2  (2, 3)  float64      6          8       48


##### Array indexing

In [4]:
a = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
             [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
             [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])
print("a:")
print(a)

a:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [5]:
# array indexing: [startindex:endindex:stepsize]
# numpy can use comma notation for greater efficiency [1, 2] > [1][2]

print("\nIndexing:")
print(a[1, 3]) # (row 1, col 2)
print(a[1, :]) # (row 1, all columns)
print(a[:, 2]) # (all rows, column 2)
print(a[2, ::2]) # (row 2, columns skipping every second)


Indexing:
14
[11 12 13 14 15 16 17 18 19 20]
[ 3 13 23]
[21 23 25 27 29]


##### Value Setting

In [6]:
# Setting values

a[1, 5] = 420.69 # numpy forces data type
print(a)
a[2, :] = 80085
print(a)
a[:, 3] = 69 # sets column 3 to 69, 69, 69
print(a)
a[:, 3] = [101, 102, 103] # sets column 3 to 101, 102, 103
print(a)
a[:, 3] = np.arange(8, 8+6, 2) # sets column 3 to 8, 10, 12
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15 420  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]]
[[    1     2     3     4     5     6     7     8     9    10]
 [   11    12    13    14    15   420    17    18    19    20]
 [80085 80085 80085 80085 80085 80085 80085 80085 80085 80085]]
[[    1     2     3    69     5     6     7     8     9    10]
 [   11    12    13    69    15   420    17    18    19    20]
 [80085 80085 80085    69 80085 80085 80085 80085 80085 80085]]
[[    1     2     3   101     5     6     7     8     9    10]
 [   11    12    13   102    15   420    17    18    19    20]
 [80085 80085 80085   103 80085 80085 80085 80085 80085 80085]]
[[    1     2     3     8     5     6     7     8     9    10]
 [   11    12    13    10    15   420    17    18    19    20]
 [80085 80085 80085    12 80085 80085 80085 80085 80085 80085]]


##### 3D Application

In [7]:
# 3D array example
b = np.array([[[1, 2, 4], 
               [3, 4, 3], 
               [5, 6, 7]], 
              [[7, 8, 32], 
               [9, 10, 22], 
               [11, 12, 3]],
              [[3, 5, 2],
               [32, 45, 23],
               [2, 32, 69]]])
print(b)

[[[ 1  2  4]
  [ 3  4  3]
  [ 5  6  7]]

 [[ 7  8 32]
  [ 9 10 22]
  [11 12  3]]

 [[ 3  5  2]
  [32 45 23]
  [ 2 32 69]]]


In [8]:
# Ndim indexing - work outside in
print(b[2, 2, 2])
print(b[:, 2, :])

69
[[ 5  6  7]
 [11 12  3]
 [ 2 32 69]]


##### Numpy array generation methods

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3, 2), dtype="int8") # data type int8

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [11]:
np.full((2, 3, 4), 99) # np.full() generates an array of any number

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [12]:
print(np.full_like(a, 3)) # np.full_like() uses another array's shape
# equal to
print(np.full(a.shape, 3))

[[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]


In [13]:
np.random.random((2, 2))

array([[0.47199794, 0.87577014],
       [0.2548508 , 0.53913366]])

In [14]:
np.random.randint(5, 10, (2, 2))

array([[8, 7],
       [7, 6]])

In [15]:
# Repeat an array
arr = np.array([[1, 2, 3]])

print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


##### Reshape & Stack

In [16]:
# reshaping an array
a = np.ones([2, 4])
print(a)

b = a.reshape([8, 1])
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [17]:
a = np.array([1, 2, 3])
b = np.ones([2, 3])
c = np.zeros([2, 1])

print(np.vstack([a, b])) # handles adding 1D array onto a 2D array
print()
print(np.hstack([c, b]))

[[1. 2. 3.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 1. 1. 1.]
 [0. 1. 1. 1.]]


### Math

##### Array Math

In [72]:
# Demonstrate numpy math
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

print(a)
print(a+10)
print(a-4)
print(a*2)
print(a/2)
print(a//2)
print(a**2)

[1 2 3 4]
[11 12 13 14]
[-3 -2 -1  0]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]


In [73]:
# trig functions
print(np.tan(a))
print(np.sin(b * (np.pi/2))) # np has built in math functions, don't use math lib

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[1. 0. 1. 0.]


In [74]:
# array math
print(a * b)
print(a + b)

[1 0 3 0]
[2 2 4 4]


##### Linear Algebra

In [75]:
# matrix multiplication
a = np.ones([2, 3])
b = np.full([3, 2], 3)

np.matmul(a, b)

array([[9., 9.],
       [9., 9.]])

In [76]:
# make identity matrix, find determinate function
print(np.identity(3))

print(np.linalg.det(np.identity(3)))


# There are many more resources on linear algebra

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


##### Statistics

In [77]:
stats = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [78]:
print(np.min(stats))
print(np.max(stats, axis=0)) # vertical (y) axis
print(np.min(stats, axis=1)) # horizontal (x) axis

1
[4 5 6]
[1 4]


In [79]:
print(np.sum(stats))
print(stats.sum())

# essentially like adding two arrays together
# sums vertically
print(np.sum(stats, axis=0))

21
21
[5 7 9]


### Copying Arrays / Memory Management
Numpy pointers are wacky

In [13]:
# Demonstrate numpy pointing errors
import numpy as np

a = np.array((1, 2, 3))
b = a # &b == &a, b points to the same memory as a
b[0] = 10 # changing b changes the same array as a
a[1] = 20 # a also changes b
print(a)
print(b)

print()

# use .copy() to avoiding overlapping references
a = np.array((1, 2, 3))
b = a.copy() # creates a separate array for b
b[0] = 10
a[1] = 20
print(a)
print(b)

[10 20  3]
[10 20  3]

[ 1 20  3]
[10  2  3]


### Importing from File

##### Importing Data
Avoiding pandas

In [12]:
# pandas visualization
import pandas as pd

df = pd.read_csv("data.txt")
print(df)

   1  13  21  11  196  75  4   3  34  6  7  8  0  1.1  2  3.1  4.1   5
0  3  42  12  33  766  75  4  55   6  4  3  4  5    6  7    0   11  12
1  1  22  33  11  999  11  2   1  78  0  1  2  9    8  7    1   76  88


In [15]:
import numpy as np

filedata = np.genfromtxt("data.txt", delimiter=',')
filedata = filedata.astype("int")

print(filedata)



[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
