##### Array Math

In [72]:
# Demonstrate numpy math
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

print(a)
print(a+10)
print(a-4)
print(a*2)
print(a/2)
print(a//2)
print(a**2)

[1 2 3 4]
[11 12 13 14]
[-3 -2 -1  0]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]


In [73]:
# trig functions
print(np.tan(a))
print(np.sin(b * (np.pi/2))) # np has built in math functions, don't use math lib

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[1. 0. 1. 0.]


In [74]:
# array math
print(a * b)
print(a + b)

[1 0 3 0]
[2 2 4 4]


##### Linear Algebra

In [75]:
# matrix multiplication
a = np.ones([2, 3])
b = np.full([3, 2], 3)

np.matmul(a, b)

array([[9., 9.],
       [9., 9.]])

In [76]:
# make identity matrix, find determinate function
print(np.identity(3))

print(np.linalg.det(np.identity(3)))


# There are many more resources on linear algebra

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


##### Statistics

In [77]:
stats = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [78]:
print(np.min(stats))
print(np.max(stats, axis=0)) # vertical (y) axis
print(np.min(stats, axis=1)) # horizontal (x) axis

1
[4 5 6]
[1 4]


In [79]:
print(np.sum(stats))
print(stats.sum())

# essentially like adding two arrays together
# sums vertically
print(np.sum(stats, axis=0))

21
21
[5 7 9]
