In [13]:
# Demonstrate numpy pointing errors
import numpy as np

a = np.array((1, 2, 3))
b = a # &b == &a, b points to the same memory as a
b[0] = 10 # changing b changes the same array as a
a[1] = 20 # a also changes b
print(a)
print(b)

print()

# use .copy() to avoiding overlapping references
a = np.array((1, 2, 3))
b = a.copy() # creates a separate array for b
b[0] = 10
a[1] = 20
print(a)
print(b)

[10 20  3]
[10 20  3]

[ 1 20  3]
[10  2  3]
