In [3]:
# Evan Ernst
import numpy as np
import pandas as pd # used to help illustrate functions

# initialize basic numpy arrays
a = np.array([1, 2, 3], dtype="int16")

b = np.array([[1.0, 2.0, 3.0], 
              [9.0, 8.0, 7.0]])

print(f"List a: {a}")
print(f"List b: \n{b}")


List a: [1 2 3]
List b: 
[[1. 2. 3.]
 [9. 8. 7.]]


In [4]:
# np.array() methods

# a.ndim gets dimensions
# a.shape gets shape
# a.size == # of elements
# a.dtype == data type of elements
# a.itemsize == bytes per item
# a.nbytes == total bytes used == (a.itemsize * a.size)

# pandas used only to illustrate various property functions
listStats = [["a", a.ndim, a.shape, a.dtype, a.size, a.itemsize, a.nbytes],
             ["b", b.ndim, b.shape, b.dtype, b.size, b.itemsize, b.nbytes]]
df = pd.DataFrame(listStats, columns=["List", ".ndim", ".shape", ".dtype", ".size", ".itemsize", ".nbytes"])
print("\n", df)


   List  .ndim  .shape   .dtype  .size  .itemsize  .nbytes
0    a      1    (3,)    int16      3          2        6
1    b      2  (2, 3)  float64      6          8       48


In [5]:
a = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
             [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
             [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])
print("a:")
print(a)

a:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [6]:
# array indexing: [startindex:endindex:stepsize]
# numpy can use comma notation for greater efficiency [1, 2] > [1][2]

print("\nIndexing:")
print(a[1, 3]) # (row 1, col 2)
print(a[1, :]) # (row 1, all columns)
print(a[:, 2]) # (all rows, column 2)
print(a[2, ::2]) # (row 2, columns skipping every second)


Indexing:
14
[11 12 13 14 15 16 17 18 19 20]
[ 3 13 23]
[21 23 25 27 29]


In [7]:
# Setting values

a[1, 5] = 420.69 # numpy forces data type
print(a)
a[2, :] = 80085
print(a)
a[:, 3] = 69 # sets column 3 to 69, 69, 69
print(a)
a[:, 3] = [101, 102, 103] # sets column 3 to 101, 102, 103
print(a)
a[:, 3] = np.arange(8, 8+6, 2) # sets column 3 to 8, 10, 12
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15 420  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]]
[[    1     2     3     4     5     6     7     8     9    10]
 [   11    12    13    14    15   420    17    18    19    20]
 [80085 80085 80085 80085 80085 80085 80085 80085 80085 80085]]
[[    1     2     3    69     5     6     7     8     9    10]
 [   11    12    13    69    15   420    17    18    19    20]
 [80085 80085 80085    69 80085 80085 80085 80085 80085 80085]]
[[    1     2     3   101     5     6     7     8     9    10]
 [   11    12    13   102    15   420    17    18    19    20]
 [80085 80085 80085   103 80085 80085 80085 80085 80085 80085]]
[[    1     2     3     8     5     6     7     8     9    10]
 [   11    12    13    10    15   420    17    18    19    20]
 [80085 80085 80085    12 80085 80085 80085 80085 80085 80085]]


In [20]:
# 3D array example
b = np.array([[[1, 2, 4], 
               [3, 4, 3], 
               [5, 6, 7]], 
              [[7, 8, 32], 
               [9, 10, 22], 
               [11, 12, 3]],
              [[3, 5, 2],
               [32, 45, 23],
               [2, 32, 69]]])
print(b)

[[[ 1  2  4]
  [ 3  4  3]
  [ 5  6  7]]

 [[ 7  8 32]
  [ 9 10 22]
  [11 12  3]]

 [[ 3  5  2]
  [32 45 23]
  [ 2 32 69]]]


In [25]:
# Ndim indexing - work outside in
print(b[2, 2, 2])
print(b[:, 2, :])

69
[[ 5  6  7]
 [11 12  3]
 [ 2 32 69]]


In [44]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3, 2), dtype="int8") # data type int8

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [49]:
np.full((2, 3, 4), 99) # np.full() generates an array of any number

array([[[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]]])

In [55]:
print(np.full_like(a, 3)) # np.full_like() uses another array's shape
# equal to
print(np.full(a.shape, 3))

[[3. 3. 3.]
 [3. 3. 3.]]
[[3 3 3]
 [3 3 3]]


In [67]:
np.random.random((2, 2))

array([[0.95823019, 0.98034197],
       [0.48498221, 0.58522484]])

In [69]:
np.random.randint(5, 10, (2, 2))

array([[9, 6],
       [6, 7]])

In [75]:
# Repeat an array
arr = np.array([[1, 2, 3]])

print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
