# Challenges

## Array Challenge
Make a 2D array with a border of 1s, center of 9(s), and the rest filled with 0s

In [80]:
import numpy as np

height = 11
width = 10

# make an NxN array of 0s
arr = np.ones((height, width), dtype="int16")

# get everything except for a border
arr[1:-1, 1:-1] = 0

# set the center square(s) to 9
arr[((arr.shape[0]-1)//2):((arr.shape[0])//2+1), # rows
    ((arr.shape[1]-1)//2):((arr.shape[1])//2+1)] = 9 # columns

print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 9 9 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
