In [2]:
# Evan Ernst - Jan 20 2024
import numpy as np
import pandas as pd # used to help illustrate functions

# illustrating property methods of numpy arrays
a = np.array([1, 2, 3], dtype="int16")

b = np.array([[1.0, 2.0, 3.0], 
              [9.0, 8.0, 7.0]])

print(f"List a: {a}")
print(f"List b: \n{b}")

# a.ndim gets dimensions
# a.shape gets shape
# a.size == # of elements
# a.dtype == data type of elements
# a.itemsize == bytes per item
# a.nbytes == total bytes used == (a.itemsize * a.size)

# pandas used only to illustrate various property functions
listStats = [["a", a.ndim, a.shape, a.dtype, a.size, a.itemsize, a.nbytes],
             ["b", b.ndim, b.shape, b.dtype, b.size, b.itemsize, b.nbytes]]
df = pd.DataFrame(listStats, columns=["List", ".ndim", ".shape", ".dtype", ".size", ".itemsize", ".nbytes"])
print("\n", df)


List a: [1 2 3]
List b: 
[[1. 2. 3.]
 [9. 8. 7.]]

   List  .ndim  .shape   .dtype  .size  .itemsize  .nbytes
0    a      1    (3,)    int16      3          2        6
1    b      2  (2, 3)  float64      6          8       48


In [3]:
# how to access elements - indexing
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
             [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

print("a:")
print(a)

# array indexing: [startindex:endindex:stepsize]
# numpy can use comma notation for greater efficiency
print("\nIndexing: a[startindex:endindex:stepsize]")
print("Numpy access: use a[row, col] instead of a[row][col] for greater efficiency\n")

print(f"a[1, 3] == {a[1, 3]}    # (row 1, col 2)")
print(f"a[1, :] == {a[1, :]}    # (row 1, all columns)")
print(f"a[:, 2] == {a[:, 2]}    # (all rows, column 2)")

print(f"\na[2, ::2] == {a[2, ::2]}    # (row 2, columns skipping every second)")

a[1, 5] = 420.69 # numpy forces data type
print("\na[1, 5] = 420.69")
print("a:\n", a)

a:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

Indexing: a[startindex:endindex:stepsize]
Numpy access: use a[row, col] instead of a[row][col] for greater efficiency

a[1, 3] == 14    # (row 1, col 2)
a[1, :] == [11 12 13 14 15 16 17 18 19 20]    # (row 1, all columns)
a[:, 2] == [ 3 13 23]    # (all rows, column 2)

a[2, ::2] == [21 23 25 27 29]    # (row 2, columns skipping every second)

a[1, 5] = 420.69
a:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15 420  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]]


range(2, 4)
[0 1 2 3 4 5 6 7 8 9]
